name: CI
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
      - name: Run pre-commit checks
        run: pixi run pre-commit
