name: CI
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
